# Generated by Django 4.1.7 on 2023-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(blank=True, default=0, null=True, upload_to='uploads/')),
            ],
        ),
    ]
